version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      
  server:
    image: server
    depends_on:
      - db
    ports:
      - '8080:8080'

  client:
    build: ./docker/client
    depends_on:
      - server
    ports:
      - '8081:8081'